### ISSUE TITLE
Actually switching to Railway for performance and getting IP addresses from proxy, not just moving DB data around

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [MadeByThePinsHub/are-we-down#78]
```
<!--
start: 2021-05-20T12:50:00.000Z
end: 2021-05-21T12:15:30.000Z
expectedDown: public-link-shortener-powered-by-thedevs-network-kutt
-->
```

**Comment by AndreiJirohHaliliDev2006** [comment]
## About this scheduled maintenance

We'll migrate our Postgres database from `development` to `production` environments in Railway. We might need to take down the current deployment to avoid chaos, and also change the DNS records of `rtapp.tk` to `thepinsteam.github.io` to tell people that we're down.

This may probably take up to 30 minutes if it's seamless, but if there are issues, we might take longer.

**Comment by AndreiJirohHaliliDev2006** [comment]
**Update**: The maintenance window has been extended by one more day to ensure everything is fine. We may start over again and manually import all the data.

**Comment by AndreiJirohHaliliDev2006** [comment]
**Update**: Importing of DB data from old Postgres instance is finished. Actually, we'll use this time to move our infrastructure for the sortlink service to Railway for us to proxy it behind Cloudflare's network.

We'll move the configuration first to Railway, then we'll automate the process of deployment process from development (may changed to `staging` probably) to production through the Pull app. Then configure the root DNS record for `rtapp.tk` to the Railway one (we don't need to worry about DNS spec violations because Cloudflare will handle it through CNAME flattening). And finally nuke the instance from Divio.

There are still some issues such as default domain and emails is undefined across the UI. (Hard-coding isn't fun), so we have implemented some `console.log` chaos in an meanwhile.

**Comment by ThePinsTeam** [comment]
**Update**: Our Kutt instance will be come back online within the next few hours, as we configure deployment triggers in Railway, among other things.

**Comment by AndreiJirohHaliliDev2006** [comment]
**Update**: The migration process has been finished and everything is fine.
